"""Build focused paper-summary tables from claim-gated result files.

Outputs written to results/paper/tables/:

  table_feature_tiers.csv          Feature-level provenance tiers (from YAML).
  table_provenance_inventory.csv   Node provenance, coverage, and claim ceiling.
  table_aa_provenance_valid_edges.csv  All A/A provenance-valid edges.
  table_aa_paper_claimable_edges.csv   A/A edges that pass both provenance + statistical gates.
  table_ab_suggestive_edges.csv    A/B edges that pass the paper gate.
  table_claim_audit_summary.csv    Per-event claim-gate counts (Table 6 / audit figure).

Usage:
    python scripts/11d_make_claim_summary_tables.py
    python scripts/11d_make_claim_summary_tables.py --paper-dir results/paper/tables
"""

from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl
import yaml

from stressnet.config import results_root
from stressnet.graph.nodes import nodes_for_event
from stressnet.utils.logging import get_logger

logger = get_logger(__name__)

_EVENTS = ["usdc_svb_2023", "terra_luna_2022", "usdt_curve_2023", "ftx_2022", "busd_2023"]
_AA_LEVELS = frozenset({
    "A_A_dex_flow",
    "A_A_onchain_settlement",
    "A_A_cex_microstructure",
    "A_A_high_provenance",
})
_BOOL_COLS = (
    "provenance_claim_allowed",
    "statistical_claim_allowed",
    "paper_claim_allowed",
    "uses_fixture",
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SKIP_PREFIXES = (
    # Claim-gate audits (summaries, not edge tables)
    "table_claim_gate",
    "table_claim_language",
    # Already-consolidated summary tables generated by 99_make_paper_outputs.py
    # or this script — reading them causes duplicate edges.
    "table_aa_amm",
    "table_aa_provenance",
    "table_aa_paper",
    "table_ab_suggestive",
    "table_provenance_claimable",
    "table_statistically_supported",
    "table_claim_audit",
    # Non-edge paper outputs
    "table_paper_summary",
    "table_node_coverage",
    "table_provenance_inventory",
    "table_feature_tiers",
    "table_event_study",
    "table_node_centrality",
    "table_prediction",
)


def _load_paper_tables(paper_dir: Path) -> pl.DataFrame | None:
    """Concatenate per-event claim-bearing result tables into one frame.

    Reads from results/paper/tables/ but skips consolidated summary tables
    to avoid double-counting the same edge from multiple aggregated files.
    Only per-event primary result files (leadlag, TE, granger, tvp_var*) are
    included so each edge row is counted exactly once.
    """
    # Read from the annotated results/tables/ dir so we get each edge once.
    src_dir = paper_dir.parent.parent / "tables"
    if not src_dir.exists():
        src_dir = paper_dir  # fallback

    frames: list[pl.DataFrame] = []
    for p in sorted(src_dir.glob("*.csv")):
        if any(p.name.startswith(pfx) for pfx in _SKIP_PREFIXES):
            continue
        if not any(p.name.startswith(pfx) for pfx in (
            "table_leadlag_tests_",
            "table_transfer_entropy_",
            "table_granger_",
            "table_tvp_var_summary_",
            "table_var_spillovers_",
            "table_sparse_events_",
        )):
            continue
        try:
            df = pl.read_csv(p)
        except Exception:
            continue
        if "claim_level" not in df.columns:
            continue
        df = df.with_columns(pl.lit(p.name).alias("source_table"))
        frames.append(df)

    if not frames:
        return None
    # Cast all columns to String before concat to avoid type-mismatch across tables.
    str_frames = [f.select([pl.col(c).cast(pl.String) for c in f.columns]) for f in frames]
    return pl.concat(str_frames, how="diagonal")


def _parse_bools(df: pl.DataFrame) -> pl.DataFrame:
    """Cast boolean-string columns to Polars Boolean."""
    for col in _BOOL_COLS:
        if col in df.columns and df[col].dtype != pl.Boolean:
            df = df.with_columns(
                (pl.col(col).cast(pl.String).str.to_lowercase().is_in(["true", "1", "yes"]))
                .alias(col)
            )
    return df


# ---------------------------------------------------------------------------
# Table 1 — feature_tiers
# ---------------------------------------------------------------------------

def write_feature_tiers(out_dir: Path) -> None:
    """Flatten configs/feature_tiers.yaml to a CSV."""
    from stressnet.config import _CONFIGS_DIR
    yaml_path = _CONFIGS_DIR / "feature_tiers.yaml"
    if not yaml_path.exists():
        logger.warning("feature_tiers.yaml not found; skipping.")
        return
    with yaml_path.open() as fh:
        raw = yaml.safe_load(fh) or {}
    features = raw.get("features", {})
    rows = []
    for feat, meta in features.items():
        rows.append({
            "feature_col":               feat,
            "tier":                      str(meta.get("tier", "B")),
            "evidence_type":             str(meta.get("evidence_type", "")),
            "claim_language":            str(meta.get("claim_language", "")),
            "effective_tier_without_l2": str(meta.get("effective_tier_without_l2", "")),
            "notes":                     str(meta.get("notes", "")).strip(),
        })
    if rows:
        df = pl.DataFrame(rows).sort("tier")
        out = out_dir / "table_feature_tiers.csv"
        df.write_csv(out)
        logger.info("Wrote %s (%d features)", out.name, df.height)


# ---------------------------------------------------------------------------
# Table 2 — provenance_inventory
# ---------------------------------------------------------------------------

def write_provenance_inventory(out_dir: Path) -> None:
    """Join node coverage with layer metadata for a paper-facing provenance table."""
    cov_path = results_root() / "tables" / "table_node_coverage.csv"
    if not cov_path.exists():
        logger.warning("table_node_coverage.csv not found; skipping provenance inventory.")
        return

    cov = pl.read_csv(cov_path).filter(pl.col("node_id") != "__event_panel__")

    # Build layer + primary-features lookup per event/node
    layer_rows: list[dict] = []
    for event_id in _EVENTS:
        for node in nodes_for_event(event_id):
            layer_rows.append({
                "event_id":    event_id,
                "node_id":     node.id,
                "layer":       getattr(node, "layer", ""),
            })
    if not layer_rows:
        logger.warning("No node metadata; provenance inventory will lack layer column.")
        layer_df = pl.DataFrame({"event_id": [], "node_id": [], "layer": []})
    else:
        layer_df = pl.DataFrame(layer_rows)

    # Derive claim ceiling from tier
    def _claim_ceiling(tier: str) -> str:
        mapping = {
            "A":                    "A/A DEX-flow, A/A settlement, A/B, B/B",
            "B":                    "A/B suggestive, B/B context",
            "C":                    "context / taxonomy only",
            "fixture_non_empirical": "not claimable",
            "missing":              "not claimable",
        }
        return mapping.get(str(tier), "unknown")

    tier_col = "source_tier_actual" if "source_tier_actual" in cov.columns else "tier_actual"
    cov = cov.join(layer_df, on=["event_id", "node_id"], how="left")
    cov = cov.with_columns(
        (pl.col(tier_col).map_elements(_claim_ceiling, return_dtype=pl.String))
        .alias("claim_ceiling"),
        (pl.col(tier_col).is_in(["fixture_non_empirical"]))
        .alias("fixture_flag"),
    )

    keep = [c for c in [
        "event_id", "node_id", "layer", tier_col,
        "sources", "coverage_pct", "rows_available",
        "fixture_flag", "claim_ceiling",
    ] if c in cov.columns]
    out = out_dir / "table_provenance_inventory.csv"
    cov.select(keep).write_csv(out)
    logger.info("Wrote %s (%d rows)", out.name, cov.height)


# ---------------------------------------------------------------------------
# Tables 3-5 — A/A valid, A/A paper, A/B suggestive
# ---------------------------------------------------------------------------

def write_aa_ab_tables(df: pl.DataFrame, out_dir: Path) -> None:
    """Write A/A provenance-valid, A/A paper-claimable, and A/B paper-claimable tables."""
    df = _parse_bools(df)

    prov_col  = "provenance_claim_allowed"
    paper_col = "paper_claim_allowed"

    # Guard: ensure columns exist
    if prov_col not in df.columns:
        df = df.with_columns(pl.lit(False).alias(prov_col))
    if paper_col not in df.columns:
        df = df.with_columns(pl.lit(False).alias(paper_col))

    # Resolve node_i / node_j regardless of column naming convention
    def _resolve_edge_cols(frame: pl.DataFrame) -> pl.DataFrame:
        """Normalise to node_i / node_j; drop self-loops."""
        if "node_i" not in frame.columns or "node_j" not in frame.columns:
            for src, tgt in [("causing_node", "caused_node"),
                             ("source_node_id", "target_node_id"),
                             ("source_node", "target_node"),
                             ("source", "target")]:
                if src in frame.columns and tgt in frame.columns:
                    frame = frame.rename({src: "node_i", tgt: "node_j"})
                    break
        # Drop self-loops (VAR/FEVD diagonal; not cross-node propagation)
        if "node_i" in frame.columns and "node_j" in frame.columns:
            frame = frame.filter(pl.col("node_i") != pl.col("node_j"))
        return frame

    df = _resolve_edge_cols(df)

    # Table 3: A/A provenance-valid (all A/A levels, provenance gate passes)
    aa_prov = df.filter(
        pl.col("claim_level").is_in(list(_AA_LEVELS))
        & pl.col(prov_col)
    )
    if aa_prov.height > 0:
        aa_prov.write_csv(out_dir / "table_aa_provenance_valid_edges.csv")
        logger.info(
            "Wrote table_aa_provenance_valid_edges.csv (%d rows, claim levels: %s)",
            aa_prov.height,
            aa_prov["claim_level"].unique().sort().to_list(),
        )
        print("\n=== A/A provenance-valid edges ===")
        print(aa_prov.group_by("claim_level").len().sort("len", descending=True))
    else:
        logger.warning("No A/A provenance-valid edges found.")

    # Table 4: A/A paper-claimable (both gates pass)
    aa_paper = df.filter(
        pl.col("claim_level").is_in(list(_AA_LEVELS))
        & pl.col(paper_col)
    )
    if aa_paper.height > 0:
        aa_paper.write_csv(out_dir / "table_aa_paper_claimable_edges.csv")
        logger.info(
            "Wrote table_aa_paper_claimable_edges.csv (%d rows) — headline A/A claims",
            aa_paper.height,
        )
        print("\n=== A/A paper-claimable edges (headline results) ===")
        display_cols = [c for c in [
            "event_id", "node_i", "node_j", "feature_col", "source_table",
            "claim_level", "claim_strength", "paper_claim_allowed",
        ] if c in aa_paper.columns]
        print(aa_paper.select(display_cols))
    else:
        logger.warning(
            "No A/A paper-claimable edges. "
            "High-provenance AMM flow is available as descriptive evidence "
            "(see table_aa_provenance_valid_edges.csv), but none pass the statistical gate. "
            "Use claim_strength='suggestive' language for these pairs."
        )

    # Table 5: A/B paper-claimable
    ab_paper = df.filter(
        (pl.col("claim_level") == "A_B_suggestive_directional")
        & pl.col(paper_col)
    )
    if ab_paper.height > 0:
        ab_paper.write_csv(out_dir / "table_ab_suggestive_edges.csv")
        logger.info(
            "Wrote table_ab_suggestive_edges.csv (%d rows) — A/B suggestive propagation",
            ab_paper.height,
        )
    else:
        logger.warning("No A/B paper-claimable edges found.")


# ---------------------------------------------------------------------------
# Table 6 — claim_audit_summary
# ---------------------------------------------------------------------------

def write_claim_audit(df: pl.DataFrame, out_dir: Path) -> None:
    """Write per-event claim-gate audit counts (Table 6, anti-cherry-pick evidence)."""
    df = _parse_bools(df)

    audit_rows: list[dict] = []
    events_in_df = (
        [e for e in df["event_id"].drop_nulls().unique().sort().to_list() if e]
        if "event_id" in df.columns else ["all"]
    )

    for event_id in events_in_df:
        g = df.filter(pl.col("event_id") == event_id) if "event_id" in df.columns else df
        prov_ok  = "provenance_claim_allowed" in g.columns
        stat_ok  = "statistical_claim_allowed" in g.columns
        paper_ok = "paper_claim_allowed" in g.columns
        fix_ok   = "uses_fixture" in g.columns

        audit_rows.append({
            "event_id":              event_id,
            "n_total_edges":         g.height,
            "n_fixture_blocked":     int(g.filter(pl.col("uses_fixture")).height) if fix_ok else 0,
            "n_provenance_claimable": int(g.filter(pl.col("provenance_claim_allowed")).height) if prov_ok else 0,
            "n_statistically_supported": int(g.filter(pl.col("statistical_claim_allowed")).height) if stat_ok else 0,
            "n_paper_claimable":     int(g.filter(pl.col("paper_claim_allowed")).height) if paper_ok else 0,
            "n_AA_provenance":       int(g.filter(
                pl.col("claim_level").is_in(list(_AA_LEVELS))
                & (pl.col("provenance_claim_allowed") if prov_ok else pl.lit(True))
            ).height),
            "n_AA_paper_claimable":  int(g.filter(
                pl.col("claim_level").is_in(list(_AA_LEVELS))
                & (pl.col("paper_claim_allowed") if paper_ok else pl.lit(False))
            ).height),
            "n_AB_paper_claimable":  int(g.filter(
                (pl.col("claim_level") == "A_B_suggestive_directional")
                & (pl.col("paper_claim_allowed") if paper_ok else pl.lit(False))
            ).height),
            "n_BB_context":          int(g.filter(
                pl.col("claim_level") == "B_B_context_only"
            ).height),
        })

    audit = pl.DataFrame(audit_rows)
    out = out_dir / "table_claim_audit_summary.csv"
    audit.write_csv(out)
    logger.info("Wrote %s (%d events)", out.name, audit.height)
    print("\n=== Claim audit summary ===")
    print(audit)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Build paper claim-summary tables.")
    parser.add_argument(
        "--paper-dir",
        default=None,
        help="Directory to read/write paper tables (default: results/paper/tables).",
    )
    args = parser.parse_args()

    paper_dir = Path(args.paper_dir) if args.paper_dir else results_root() / "paper" / "tables"
    paper_dir.mkdir(parents=True, exist_ok=True)

    # 1. Feature-tier table (from YAML — no paper tables needed)
    write_feature_tiers(paper_dir)

    # 2. Provenance inventory (from node coverage + configs)
    write_provenance_inventory(paper_dir)

    # 3-6. Load all claim-bearing paper tables
    combined = _load_paper_tables(paper_dir)
    if combined is None:
        logger.error(
            "No claim-bearing paper tables found in %s. "
            "Run 00c_claim_gate.py --all-events --strict first.",
            paper_dir,
        )
        raise SystemExit(1)

    write_aa_ab_tables(combined, paper_dir)
    write_claim_audit(combined, paper_dir)

    logger.info("Claim summary tables complete.")


if __name__ == "__main__":
    main()
